defaults:
  - _self_
  - agent: random
  - search_space: random_seed
  - override hydra/sweeper: HyperRS

hydra:
  sweeper:
    n_trials: 5
    search_space: ${search_space}
  run:
    dir: "${outpath}/${agent_name}/${env_name}/seed_${seed}"
  sweep:
    dir: "${outpath}/${agent_name}/${env_name}/"
  
seed: 0
training_steps: 1e5
env_name: Pendulum-v1
env_kwargs: {}
agent_kwargs: {}
eval_every_n_steps: 1000
n_eval_episodes: 1
outpath: "hpo_results_rs"
buffer_cls: SimpleBuffer
buffer_kwargs: {}
batch_size: 64
update_after_episode_end: false